
# Shell generated by LLM, modified by me--------*
def main():
    running = True

    while running:
        print("\nChoose an option:")
        print("1. Create new db")
        print("2. Upload new csv file")
        print("3. Begin Query")
        print("4. Exit")

        user_choice = input("Enter your choice: ").strip()

        if user_choice == "1":
            # add logic for option one
            pass
        elif user_choice == "2":
            # add logic for option two
            pass
        elif user_choice == "3":
            print("Exiting program.")
            running = False
        else:
            print("Invalid input. Please try again.")

if __name__ == "__main__":
    main()
# Shell generated by LLM, modified by me--------*
