from csv_loader_logic import upload_data


# Shell generated by LLM, modified by me--------*
def main():
    running = True

    while running:
        print("\nChoose an option:")
        print("1. Create new db")
        print("2. Upload new csv file")
        print("3. Query db")
        print("4. Exit")

        user_choice = input("Enter your choice: ").strip()

        if user_choice == "1":
            user_input = input("What is the name of the db you would like to create?: ").strip()
            upload_data(user_input)
            pass
        elif user_choice == "2":
            user_input = input("What is the name of the csv file you want to add?").strip()

            # add logic for option two
            pass
        elif user_choice == "3":
            print("Exiting program.")
            running = False
        else:
            print("Invalid input. Please try again.")

if __name__ == "__main__":
    main()
# Shell generated by LLM, modified by me--------*
