import pandas as pd
import sqlite3

# Thought about SQL injection and passing parameterized values vs commands. Discussed with ChatGPT,
# suggestion was to validate entries. Given that the data types are generated by the type of data stored,
# I don't think this could be a source of injection. Need to validate the column headers though as those could
# contain issues.


# Schema Manager Part 1
# Generated by LLM, modified by me--------*
def pandas_to_sqlite_type(dtype) -> str:
    if pd.api.types.is_integer_dtype(dtype):
        return "INTEGER"
    if pd.api.types.is_float_dtype(dtype):
        return "REAL"
    if pd.api.types.is_bool_dtype(dtype):
        return "INTEGER"
    return "TEXT"
# Generated by LLM, modified by me--------*

# Generated by LLM--------*
def create_schema_record(df: pd.DataFrame) -> str:
    if not hasattr(create_schema_record, "counter"):
        create_schema_record.counter = 1

    table_name = f"Table_{create_schema_record.counter}"
    create_schema_record.counter += 1

    column_defs = ['"primary_key_index" INTEGER PRIMARY KEY AUTOINCREMENT']
    for col_name, dtype in df.dtypes.items():
        sqlite_type = pandas_to_sqlite_type(dtype)
        column_defs.append(f'"{col_name}" {sqlite_type}')

    columns_sql = ", ".join(column_defs)
    return f'CREATE TABLE "{table_name}" ({columns_sql});'
# Generated by LLM--------*

# Schema Manager Part 2
# Generated by LLM--------*
def get_all_schema_strings(db_path: str) -> list[str]:
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute("""
        SELECT sql
        FROM sqlite_master
        WHERE type = 'table'
        AND name NOT LIKE 'sqlite_%'
    """)

    results = cursor.fetchall()
    conn.close()

    return [row[0] for row in results]
# Generated by LLM--------*


