import pandas as pd
from schema_manager import create_schema_record
from db_modifier import modify_sql_db_table
from human_itl import human_itl_confirms

def upload_data(table_path: str, db_name: str):
    # Step 1: Convert csv file into a df
    # generated by LLM--------*
    try:
        df = pd.read_csv(table_path)
    except TypeError:
        raise
    # generated by LLM--------*

    # Step 2: call schema manager. SM will make a new schema record for this uploaded data.
    table_name = table_path[:-4]
    create_table_str = create_schema_record(df, table_name)

    # Step 3:
    if human_itl_confirms("Do you want to execute this change to the database?", create_table_str):
        modify_sql_db_table(create_table_str, df, db_name, table_name)

    # LLM suggestion
    return {"status": "success", "table": table_name}