import pandas as pd
from schema_manager import create_schema_record
from db_modifier import modify_sql_add_table

def upload_data(table_path: str, db_name: str):
    # Step 1: Convert csv file into a df
    # generated by LLM--------*
    try:
        df = pd.read_csv(table_path)
    # TODO: If you do not know them yet, test, inspect, and log the real exception type first.
    except Exception as e:
        print(type(e).__name__, e)
        raise
    # generated by LLM--------*

    # Step 2: call schema manager. SM will make a new schema record for this uploaded data.
    table_name = table_path[:-4]
    create_table_str = create_schema_record(df, table_name)

    # Step 3:
    modify_sql_add_table(create_table_str, df, db_name, table_name)


