# https://news.ycombinator.com/item?id=42095012
import sqlite3
import pandas as pd


# TODO: right now isn't read only, can write as well.
def query_only_db(query_db_sql_command: str, db_name: str):
    # query (connect only with read only for query) But can write via the sqlite_db
    conn = sqlite3.connect(db_name)
    cur = conn.cursor()

    try:
        db_response = cur.execute(query_db_sql_command).fetchone()
    except Exception as e:
        raise

    conn.close()
    print("db_modifier.py", db_response)

    return db_response

def modify_sql_add_table(modify_db_sql_command: str, df: pd.DataFrame,  db_name: str, table_name: str):
    # will create this db if it does not exist
    conn = sqlite3.connect(db_name)
    cur = conn.cursor()
    print("This is the SQL command that will be used to create a new table: ", modify_db_sql_command)
    user_choice = input("Do you want to proceed with this command? Type CONFIRM"
                        " to proceed. Type any other letter to cancel this process:   ").strip()
    if user_choice == "CONFIRM":
        print("creating table ", table_name)
        cur.execute(modify_db_sql_command)
        res = cur.execute(f"SELECT name FROM sqlite_master WHERE name='{table_name}'")
        did_it_work = res.fetchone()

        # If a table called table_name was not created, then this line will return None and an Exception will be returned
        if did_it_work is None:
            raise TypeError('table create failed')
        if did_it_work is not None:
            print(f"{table_name} created")
            # Generated by LLM--------*
            cols = ", ".join(df.columns)
            bind_data = ", ".join("?" for _ in df.columns)
            cur.executemany(
                f"INSERT INTO {table_name} ({cols}) VALUES ({bind_data})",
                df.itertuples(index=False, name=None)
            )
            # Generated by LLM--------*
            conn.commit()
            for row in cur.execute(f"SELECT * FROM {table_name};"):
                print(row)

    conn.close()
