# https://news.ycombinator.com/item?id=42095012
import sqlite3
import pandas as pd
import os
from human_itl import human_itl_confirms

def query_only_db(query_db_sql_command: str, db_name: str):
    abs_path = os.path.abspath(db_name)
    if not os.path.exists(abs_path):
        raise FileNotFoundError(f"Database file not found: {abs_path}")

    conn = sqlite3.connect(f"file:{abs_path}?mode=ro", uri=True)
    cur = conn.cursor()

    try:
        db_response = cur.execute(query_db_sql_command).fetchone()
    except Exception as e:
        raise

    conn.close()
    return db_response

def query_sql_db(db_name: str, db_command: str):
    # opens a connection between sqlite3 and the db
    conn = sqlite3.connect(f"file:{db_name}?mode=ro", uri=True)
    # conn represents a connection to db
    # cur executes SQL statements and fetches results
    cur = conn.cursor()
    # execute actually sends the command
    cur.execute(db_command)
    results = cur.fetchall()
    conn.close()
    return results


def modify_sql_add_table(modify_db_sql_command: str, df: pd.DataFrame,  db_name: str, table_name: str):
    # will create this db if it does not exist
    conn = sqlite3.connect(db_name)
    cur = conn.cursor()
    # TODO incorporate Human in the loop here
    if human_itl_confirms("Do you want to execute this change to the database?", modify_db_sql_command):
        cur.execute(modify_db_sql_command)
        res = cur.execute(f"SELECT name FROM sqlite_master WHERE name='{table_name}'")
        did_it_work = res.fetchone()

        # If a table called table_name was not created, then this line will return None and an Exception will be returned
        if did_it_work is None:
            raise TypeError('table create failed')
        if did_it_work is not None:
            print(f"{table_name} created")
            # Generated by LLM--------*
            cols = ", ".join(df.columns)
            bind_data = ", ".join("?" for _ in df.columns)
            cur.executemany(
                f"INSERT INTO {table_name} ({cols}) VALUES ({bind_data})",
                df.itertuples(index=False, name=None)
            )
            # Generated by LLM--------*
            conn.commit()
            for row in cur.execute(f"SELECT * FROM {table_name} LIMIT 3;"):
                print(row)

    conn.close()


def modify_sql_db():
    return 0



