from csv_loader import upload_data
from query_service import get_query

# Shell generated by LLM, modified by me--------*
def main():
    running = True

    while running:
        print("\nChoose an option:")
        print("1. Create a new table with entries in a new or existing database")
        print("2. Query db")
        print("3. Exit")

        user_choice = input("Enter your choice: ").strip()

        if user_choice == "1":
            db_name = input("Name of database: ").strip()
            file_path = input("File path to csv file: ").strip()
            upload_data(file_path, db_name)
            pass
        elif user_choice == "2":
            db_name = input("Name of database: ").strip()
            user_query = input("Type query here: ").strip()
            get_query(user_query, db_name)
            pass
        elif user_choice == "3":
            print("Exiting program.")
            running = False
        else:
            print("Invalid input. Please try again.")

if __name__ == "__main__":
    main()
# Shell generated by LLM, modified by me--------*
