from csv_loader import upload_data


# Shell generated by LLM, modified by me--------*
def main():
    running = True

    while running:
        print("\nChoose an option:")
        print("1. Create a new table with entries in a new or existing database")
        print("2. Query db")
        print("3. Exit")

        user_choice = input("Enter your choice: ").strip()

        if user_choice == "1":
            db_name = input("Name of DB: ").strip()
            # TODO: future feature could include supporting handling of csv file: headers, NaN, blank rows, etc.
            file_path = input("File path to csv file: ").strip()
            print(upload_data(file_path, db_name))
            pass
        elif user_choice == "2":
            user_query = input("Type query here: ").strip()
            # upload_data(user_query)
            pass
        elif user_choice == "4":
            print("Exiting program.")
            running = False
        else:
            print("Invalid input. Please try again.")

if __name__ == "__main__":
    main()
# Shell generated by LLM, modified by me--------*
