import pandas as pd
import sqlite3
import os

from db_modifier import query_sql_db, query_only_db


# Schema Manager Part 1
# Generated by LLM, modified by me--------*
def pandas_to_sqlite_type(dtype) -> str:
    if pd.api.types.is_integer_dtype(dtype):
        return "INTEGER"
    if pd.api.types.is_float_dtype(dtype):
        return "REAL"
    if pd.api.types.is_bool_dtype(dtype):
        return "INTEGER"
    return "TEXT"
# Generated by LLM, modified by me--------*

# Generated by LLM--------*
def create_schema_record(df: pd.DataFrame, table_name: str) -> str:
    #column_defs = ['"primary_key_index" INTEGER PRIMARY KEY AUTOINCREMENT']
    column_defs = []
    for col_name, dtype in df.dtypes.items():
        sqlite_type = pandas_to_sqlite_type(dtype)
        column_defs.append(f'"{col_name}" {sqlite_type}')

    columns_sql = ", ".join(column_defs)
    return f'CREATE TABLE "{table_name}" ({columns_sql});'
# Generated by LLM--------*

# Generated by LLM + Kelsey--------*
def get_list_table_names(db_path: str) -> dict:
    abs_path = os.path.abspath(db_path)
    if not os.path.exists(abs_path):
        raise FileNotFoundError(f"Database file not found: {abs_path}")

    db_table_column_dict = {}
    results = query_sql_db(db_path,"SELECT name FROM sqlite_master;")
    for row in results:
        db_table_column_dict[row[0]] = []

    return db_table_column_dict
# Generated by LLM + Kelsey--------*

# Generated by LLM + Kelsey--------*
def add_col_names(db_path: str, db_dict: dict) -> dict:
    abs_path = os.path.abspath(db_path)
    if not os.path.exists(abs_path):
        raise FileNotFoundError(f"Database file not found: {abs_path}")

    for table_name in db_dict:
        # Calls db_modifier
        results = query_sql_db(abs_path, f"PRAGMA table_info({table_name});")
        for row in results:
            db_dict[table_name].append(row[1])

    return db_dict
# Generated by LLM + Kelsey--------*


