import pandas as pd
import sqlite3
import os

# Schema Manager Part 1
# Generated by LLM, modified by me--------*
def pandas_to_sqlite_type(dtype) -> str:
    if pd.api.types.is_integer_dtype(dtype):
        return "INTEGER"
    if pd.api.types.is_float_dtype(dtype):
        return "REAL"
    if pd.api.types.is_bool_dtype(dtype):
        return "INTEGER"
    return "TEXT"
# Generated by LLM, modified by me--------*

# Generated by LLM--------*
def create_schema_record(df: pd.DataFrame, table_name: str) -> str:

    #column_defs = ['"primary_key_index" INTEGER PRIMARY KEY AUTOINCREMENT']
    column_defs = []
    for col_name, dtype in df.dtypes.items():
        sqlite_type = pandas_to_sqlite_type(dtype)
        column_defs.append(f'"{col_name}" {sqlite_type}')

    columns_sql = ", ".join(column_defs)
    return f'CREATE TABLE "{table_name}" ({columns_sql});'
# Generated by LLM--------*

# Schema Manager Part 2
# Generated by LLM--------*
# def get_all_schema_strings(db_path: str) -> list[str]:
#     abs_path = os.path.abspath(db_path)
#
#     if not os.path.exists(abs_path):
#         raise FileNotFoundError(f"Database file not found: {abs_path}")
#
#     conn = sqlite3.connect(abs_path)
#     try:
#         cursor = conn.cursor()
#         cursor.execute("""
#             SELECT sql
#             FROM sqlite_master
#             WHERE type = 'table'
#             AND name NOT LIKE 'sqlite_%'
#             AND sql IS NOT NULL
#         """)
#         results = cursor.fetchall()
#         # debugging only. maybe for output to show to user what is all in db?
#         #for i in results:
#             #print(i[0])
#         return [row[0] for row in results]
#     finally:
#         conn.close()
# Generated by LLM--------*

# Generated by LLM + Kelsey--------*
def get_list_table_names(db_path: str) -> dict:
    abs_path = os.path.abspath(db_path)
    if not os.path.exists(abs_path):
        raise FileNotFoundError(f"Database file not found: {abs_path}")

    conn = sqlite3.connect(abs_path)
    db_table_column_dict = {}
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master;")
        results = cursor.fetchall()
        for row in results:
            db_table_column_dict[row[0]] = []
    finally:
        conn.close()

    return db_table_column_dict
# Generated by LLM + Kelsey--------*

# Generated by LLM + Kelsey--------*
def add_col_names(db_path: str, db_dict: dict) -> dict:
    abs_path = os.path.abspath(db_path)
    if not os.path.exists(abs_path):
        raise FileNotFoundError(f"Database file not found: {abs_path}")

    conn = sqlite3.connect(abs_path)
    for table_name in db_dict:
        cursor = conn.cursor()
        cursor.execute(f"PRAGMA table_info({table_name});")
        results = cursor.fetchall()
        for row in results:
            db_dict[table_name].append(row[1])
    conn.close()
    return db_dict
# Generated by LLM + Kelsey--------*


