from schema_manager import get_list_table_names, add_col_names
import re
import logging

# Mostly generated by prompting ChatGPT

logging.basicConfig(
    filename="query_validator.log",
    level=logging.ERROR,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger(__name__)

def starts_with_select(query: str) -> bool:
    if not query.startswith("select"):
        logger.error(f"Rejected (does not start with SELECT): {query}")
        return False
    return True

def only_one_query(query: str) -> bool:
    if query.count(';') > 1:
        logger.error(f"Rejected (multiple queries): {query}")
        return False
    return True

def contains_forbidden_keywords(query: str) -> bool:
    FORBIDDEN_KEYWORDS = [
        "drop",
        "delete",
        "insert",
        "update",
        "alter",
        "create",
        "replace",
        "truncate",
        "attach",
        "detach",
        "pragma"
    ]
    q = query.lower()

    for keyword in FORBIDDEN_KEYWORDS:
        pattern = r"\b" + keyword + r"\b"
        # looks through entire string and success = first match found
        if re.search(pattern, q):
            logger.error(f"Rejected (forbidden keywords): {query}")
            return True

    return False

def validate_LLM_output(llm_sql_syntax: str, schema_context: dict)-> bool:
    sql_query = llm_sql_syntax.strip().lower()

    if not starts_with_select(sql_query):
        return False

    # No semicolons
    if not only_one_query(sql_query):
        return False

    if contains_forbidden_keywords(sql_query):
        return False

    # TODO: does the LLM's query only reference available tables and relevant columns
    return True
